server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://mydb.cte24o88i4yg.ap-south-1.rds.amazonaws.com:3306/testdb
    username: admin
    password: prahlad!yadav

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true